apiVersion: v1
data:
  DJANGO_SECRET: '"django-insecure-r&6rz(aj^83=h882#9ou^b(&#l@ir_-jb*7))d*x%@e6^9cmv#"'
  POSTGRES_DB: mydb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: postgres
  postgres_port: "5432"
  postgres_url: postgresql
  redis_port: "6379"
  redis_url: redis
kind: ConfigMap
metadata:
  name: app-env
  namespace: crochet
