apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: crochet
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/proj/postgres"
