# Generated by Django 6.0.7 on 2026-07-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='b',
            field=models.SmallIntegerField(default=255),
        ),
        migrations.AddField(
            model_name='light',
            name='brightness',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='light',
            name='g',
            field=models.SmallIntegerField(default=255),
        ),
        migrations.AddField(
            model_name='light',
            name='r',
            field=models.SmallIntegerField(default=255),
        ),
    ]
