# Generated by Django 6.0.7 on 2026-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
